version: '3'

services:
  db_os: 
    image:  mysql:5.7
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: jack
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb

  wordpressos: 
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on:
      - db_os
    ports:
      - 8096:80
    environment: 
      WORDPRESS_DB_HOST: db_os
      WORDPRESS_DB_USER: jack
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wp_storage_new:/var/www/html

volumes:
      wp_storage_new:
      mysql_storage_new:
